services:
  - type: web
    name: botpress-v12
    env: node
    buildCommand: |
      npm install --legacy-peer-deps
    startCommand: |
      ./bp
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: BP_PRODUCTION
        value: "true"
      - key: BPFS_STORAGE
        value: database
      - key: DATABASE_URL
        fromDatabase:
          name: botpress-db
          property: connectionString
      - key: PORT
        value: "3000"

databases:
  - name: botpress-db
    plan: free
    
